const dummyData = [
	{
		id: 1,
		name: 'John Doe',
		designation: 'Software Engineer',
		phone: '+1 (123) 456-7890',
		email: 'john.doe@example.com',
	},
	{
		id: 2,
		name: 'Jane Smith',
		designation: 'Data Analyst',
		phone: '+1 (234) 567-8901',
		email: 'jane.smith@example.com',
	},
	{
		id: 3,
		name: 'Michael Johnson',
		designation: 'Product Manager',
		phone: '+1 (345) 678-9012',
		email: 'michael.johnson@example.com',
	},
	{
		id: 4,
		name: 'Emily Brown',
		designation: 'UX Designer',
		phone: '+1 (456) 789-0123',
		email: 'emily.brown@example.com',
	},
	{
		id: 5,
		name: 'Christopher Lee',
		designation: 'Marketing Specialist',
		phone: '+1 (567) 890-1234',
		email: 'christopher.lee@example.com',
	},
	{
		id: 6,
		name: 'Olivia Wilson',
		designation: 'Sales Representative',
		phone: '+1 (678) 901-2345',
		email: 'olivia.wilson@example.com',
	},
	{
		id: 7,
		name: 'William Taylor',
		designation: 'Financial Analyst',
		phone: '+1 (789) 012-3456',
		email: 'william.taylor@example.com',
	},
	{
		id: 8,
		name: 'Emma Martinez',
		designation: 'HR Manager',
		phone: '+1 (890) 123-4567',
		email: 'emma.martinez@example.com',
	},
	{
		id: 9,
		name: 'Aiden Anderson',
		designation: 'Quality Assurance',
		phone: '+1 (901) 234-5678',
		email: 'aiden.anderson@example.com',
	},
	{
		id: 10,
		name: 'Sophia Hernandez',
		designation: 'Systems Analyst',
		phone: '+1 (012) 345-6789',
		email: 'sophia.hernandez@example.com',
	},
	{
		id: 11,
		name: 'Lucas Young',
		designation: 'Network Engineer',
		phone: '+1 (123) 456-7890',
		email: 'lucas.young@example.com',
	},
	{
		id: 12,
		name: 'Mia Green',
		designation: 'Content Writer',
		phone: '+1 (234) 567-8901',
		email: 'mia.green@example.com',
	},
	{
		id: 13,
		name: 'Liam Rodriguez',
		designation: 'Graphic Designer',
		phone: '+1 (345) 678-9012',
		email: 'liam.rodriguez@example.com',
	},
	{
		id: 14,
		name: 'Ava Perez',
		designation: 'Customer Support',
		phone: '+1 (456) 789-0123',
		email: 'ava.perez@example.com',
	},
	{
		id: 15,
		name: 'Noah Flores',
		designation: 'Business Analyst',
		phone: '+1 (567) 890-1234',
		email: 'noah.flores@example.com',
	},
	{
		id: 16,
		name: 'Isabella Butler',
		designation: 'Project Manager',
		phone: '+1 (678) 901-2345',
		email: 'isabella.butler@example.com',
	},
	{
		id: 17,
		name: 'James Barnes',
		designation: 'Software Developer',
		phone: '+1 (789) 012-3456',
		email: 'james.barnes@example.com',
	},
	{
		id: 18,
		name: 'Amelia Price',
		designation: 'Marketing Manager',
		phone: '+1 (890) 123-4567',
		email: 'amelia.price@example.com',
	},
	{
		id: 19,
		name: 'Benjamin Howard',
		designation: 'UX/UI Designer',
		phone: '+1 (901) 234-5678',
		email: 'benjamin.howard@example.com',
	},
	{
		id: 20,
		name: 'Charlotte Kelly',
		designation: 'Sales Manager',
		phone: '+1 (012) 345-6789',
		email: 'charlotte.kelly@example.com',
	},
	{
		id: 21,
		name: 'Henry Ward',
		designation: 'Financial Consultant',
		phone: '+1 (123) 456-7890',
		email: 'henry.ward@example.com',
	},
	{
		id: 22,
		name: 'Ella Collins',
		designation: 'HR Specialist',
		phone: '+1 (234) 567-8901',
		email: 'ella.collins@example.com',
	},
	{
		id: 23,
		name: 'Alexander Bennett',
		designation: 'Quality Assurance',
		phone: '+1 (345) 678-9012',
		email: 'alexander.bennett@example.com',
	},
	{
		id: 24,
		name: 'Grace Murphy',
		designation: 'Systems Administrator',
		phone: '+1 (456) 789-0123',
		email: 'grace.murphy@example.com',
	},
	{
		id: 25,
		name: 'Jackson Hall',
		designation: 'Data Scientist',
		phone: '+1 (567) 890-1234',
		email: 'jackson.hall@example.com',
	},
	{
		id: 26,
		name: 'Lily Adams',
		designation: 'Network Administrator',
		phone: '+1 (678) 901-2345',
		email: 'lily.adams@example.com',
	},
	{
		id: 27,
		name: 'Daniel Cook',
		designation: 'Content Manager',
		phone: '+1 (789) 012-3456',
		email: 'daniel.cook@example.com',
	},
	{
		id: 28,
		name: 'Sophie White',
		designation: 'Customer Relations',
		phone: '+1 (890) 123-4567',
		email: 'sophie.white@example.com',
	},
	{
		id: 29,
		name: 'Matthew Scott',
		designation: 'Business Consultant',
		phone: '+1 (901) 234-5678',
		email: 'matthew.scott@example.com',
	},
	{
		id: 30,
		name: 'Chloe Turner',
		designation: 'Marketing Coordinator',
		phone: '+1 (012) 345-6789',
		email: 'chloe.turner@example.com',
	},
];

module.exports = dummyData;